FROM node:alpine

ENV NODE_ENV=production
# ENV MONGODB_URI=mongodb://localhost/conduit

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY npm-shrinkwrap.json ./
RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 2000
CMD [ "node", "app.js" ]